import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { createAdminClient } from "@/lib/supabase/admin";
import { AudienceBriefView } from "@/components/briefs/audience-brief-view";
import { Button } from "@/components/ui/button";
import { ArrowLeft, ArrowRight } from "lucide-react";
import type { BriefContent } from "@/types/database";

interface Props {
  params: Promise<{ subreddit: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { subreddit } = await params;
  return {
    title: `r/${subreddit} Audience Brief (Sample) | RedIntelli`,
    description: `See what RedIntelli reveals about r/${subreddit}: pain points, language patterns, content strategy, and rules. Free sample audience brief.`,
  };
}

export default async function SampleBriefPage({ params }: Props) {
  const { subreddit } = await params;
  const admin = createAdminClient();

  // Find the most recent completed cached brief for this subreddit
  const { data: brief } = await admin
    .from("audience_briefs")
    .select("*")
    .eq("subreddit_id", subreddit)
    .eq("status", "completed")
    .order("created_at", { ascending: false })
    .limit(1)
    .single();

  if (!brief) {
    notFound();
  }

  const content = brief.content as BriefContent;

  return (
    <div className="mx-auto max-w-3xl px-6 py-16 sm:py-24">
      <Button variant="ghost" size="sm" asChild className="mb-8">
        <Link href="/">
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to home
        </Link>
      </Button>
      <div className="mb-12">
        <p className="text-sm font-medium uppercase tracking-widest text-muted-foreground">
          Sample audience brief
        </p>
        <h1 className="mt-3 text-3xl font-bold sm:text-4xl">
          r/{subreddit}
        </h1>
        <p className="mt-4 text-lg text-muted-foreground">
          This is a real audience brief generated by RedIntelli. Every insight
          is sourced from actual Reddit posts and comments.
        </p>
      </div>

      <AudienceBriefView
        subredditId={subreddit}
        content={content}
        createdAt={brief.created_at}
      />

      <div className="mt-16 rounded-xl border bg-muted/20 p-8 text-center">
        <h2 className="text-xl font-semibold">
          Want a brief for your subreddit?
        </h2>
        <p className="mt-2 text-muted-foreground">
          Generate your first audience brief in under two minutes. Free, no
          credit card required.
        </p>
        <Button size="lg" className="mt-6" asChild>
          <Link href="/signup">
            Get your first brief free
            <ArrowRight className="ml-2 h-4 w-4" />
          </Link>
        </Button>
      </div>
    </div>
  );
}
